### PR TITLE
Enable testnet deploys and generation of client secret files

### PR DESCRIPTION
**Pull request by iamalwaysuncomfortable**
This PR
*Enable deploys of testnet instances
*Creates a secrets file that can be used in client secret files

### CODE REVIEW

**Review by itdaniher — APPROVED** [review]
CUTE AND GOOD. JUST LIKE YOU.

**Comment by technillogue** [comment]
bumping this, is needed for the setting up echopay tutorial faeries is working on

**Comment by itdaniher** [comment]
I added invocations to the readme, need to edit this!

**Comment by technillogue** [comment]
i am once again asking you to merge this

**Review by itdaniher — APPROVED** [review]
want to change this to `cat rootcrt.pem |base64 --wrap=0)` but merging then fixing...

**Pull request merged**
